schedule_play_job:
  cron: "*/3 * * * *"
  class: "PlayWorker"
  queue: default
  active_job: true

schedule_money_job:
  cron: "0 0 * * * Chile/Santiago"
  class: "RefillMoneyWorker"
  queue: default
  active_job: true